name: cyclechallenge
description: 'Cycle Challenge'
publish_to: 'none'
version: 1.0.0+1


environment:
  sdk: '>=3.1.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.0
  get: ^4.6.6
  carousel_slider: ^4.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/font/Pretendard-Thin.ttf
          weight: 100
        - asset: assets/font/Pretendard-ExtraLight.ttf
          weight: 200
        - asset: assets/font/Pretendard-Light.ttf
          weight: 300
        - asset: assets/font/Pretendard-Regular.ttf
          weight: 400
        - asset: assets/font/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/font/Pretendard-SemiBold.ttf
          weight: 600
        - asset: assets/font/Pretendard-Bold.ttf
          weight: 700
        - asset: assets/font/Pretendard-ExtraBold.ttf
          weight: 800

